name: create aws infra
on:
  push:
    branches:
      - master
jobs:
  create_plan:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: set-up terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: setup aws-cli
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GIT_TOKEN }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: test aws login
        run: | 
          aws sts get-caller-identity
      - name: initialize, format and plan
        run: |
          terraform init
          terraform fmt
          terraform plan -out myplan
      # - name: apply
      #   run: terraform apply myplan
      - name: get statefile   
        uses: actions/upload-artifact@v4
        with:
          name: myplan
          path: ./myplan
